// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtH_9buk7ZEAUifv68u48rgIICmTCRiZA',
    appId: '1:797929813540:web:b74cb5dcfb7afc381e0ab1',
    messagingSenderId: '797929813540',
    projectId: 'first-app-37d5a',
    authDomain: 'first-app-37d5a.firebaseapp.com',
    databaseURL: 'https://first-app-37d5a-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-37d5a.firebasestorage.app',
    measurementId: 'G-41M0S368GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6pp5BxYXt2FW5Jx3l2KeHALvogXFRJwE',
    appId: '1:797929813540:android:4b68c8c8cf390e2b1e0ab1',
    messagingSenderId: '797929813540',
    projectId: 'first-app-37d5a',
    databaseURL: 'https://first-app-37d5a-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-37d5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr-btvMFfRJTSihPoLU2Gp288J5DvXgeA',
    appId: '1:797929813540:ios:8681636d121edb961e0ab1',
    messagingSenderId: '797929813540',
    projectId: 'first-app-37d5a',
    databaseURL: 'https://first-app-37d5a-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-37d5a.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr-btvMFfRJTSihPoLU2Gp288J5DvXgeA',
    appId: '1:797929813540:ios:8681636d121edb961e0ab1',
    messagingSenderId: '797929813540',
    projectId: 'first-app-37d5a',
    databaseURL: 'https://first-app-37d5a-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-37d5a.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtH_9buk7ZEAUifv68u48rgIICmTCRiZA',
    appId: '1:797929813540:web:0105741698b426671e0ab1',
    messagingSenderId: '797929813540',
    projectId: 'first-app-37d5a',
    authDomain: 'first-app-37d5a.firebaseapp.com',
    databaseURL: 'https://first-app-37d5a-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-37d5a.firebasestorage.app',
    measurementId: 'G-GPCV7C1M2C',
  );
}
